### ISSUE TITLE
set default values back

### ISSUE THREAD

**Issue by apple-corps** [whyakari/TermuxDisableProcces#2]
So what are the default values to "re-enable" ?

> adb shell "/system/bin/device_config set_sync_disabled_for_tests persistent"

> adb shell "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"

> adb shell settings put global settings_enable_monitor_phantom_procs false

For example I think one of them is 

adb shell settings put global settings_enable_monitor_phantom_procs true

perhaps this is 20

adb shell "/system/bin/device_config put activity_manager max_phantom_processes 20

and not sure what value is default here

> adb shell "/system/bin/device_config set_sync_disabled_for_tests ..."

It's always good to provide "reversal" or "re-enable" steps.

**Comment by apple-corps** [comment]
Someone mentioned that rebooting will reset this configuration.

**Comment by whyakari** [comment]
@apple-corps I have no idea. I suggest looking at the original source where it talks about termux processes and etc. I will close because this problem is not to be solved here. go to [here](https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8) and I suggest to close the issue

**Comment by rua-666** [comment]
The default value is none
adb shell cmd device_config set_sync_disabled_for_tests none
